#!C:/Users/DELL/AppData/Local/Programs/Python/Python39/python.exe
print("Content-type:text/html \r\n\r\n")
import cgitb;cgitb.enable()
import pymysql as p
import cgi
conn=p.connect(host="localhost",user="root",password="",database="fest")
cur=conn.cursor()
f=cgi.FieldStorage()
id=f.getvalue("id")
rid=f.getvalue("rid")
q="""delete from volunteer_reg where id='%s'""" %(rid)
cur.execute(q)
conn.commit()
print("""
        <script>
        alert("successfully deleted");
        location.href="volunteer_view.py?id=%s";
        </script>
        """%(id))
