#!C:/Users/DELL/AppData/Local/Programs/Python/Python39/python.exe
print("Content-type:text/html \r\n\r\n")
import cgi, cgitb;cgitb.enable()
import pymysql
conn = pymysql.connect(host="localhost", user="root", password="", database="fest")
cur = conn.cursor()
q1 = """select max(id) from event_reg"""
cur.execute(q1)
r = cur.fetchone()
if r[0] != None:
    n = r[0]
else:
    n = 0
z = ""
if n < 10:
    z = "000"
elif n < 100:
    z = "00"
elif n < 1000:
    z = "0"
else:
    z = ""
eid="event"+z+str(n + 1)
print("""
<html>  
<head>   
<title>Sports registration</title>
<link rel="stylesheet" type="text/css" href="styles/styles1.css">
<link  rel="icon" type="logo/icon" href="images/logo.jpg">
<link rel="stylesheet" type="text/css" href="styles/css/bootstrap.min.css">
<script src="styles/js/jquery.min.js"></script>
<script src="styles/js/bootstrap.min.js"></script>
<style>
	* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Verdana,Grande,Fahoma,sans-serif;
}

.header {
  overflow: hidden;
  background-color:mediumseagreen;
  padding: 3px 10px;
}

.header a {
  float: left;
  color: blue;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }

  .header-right {
    float: none;
  }
}

	body{
		margin:0px;
		padding:0px;
		background-image:url('images/sports.jpg');
		background-repeat:no-repeat;
		background-size:100% 1500px;
		background-size:cover;
		}
	.simple-form{
		text-align:center;
		margin:100px 400px;
		}
	#registration{
		margin:auto;
		width:80%;
		background-color:gray;
		text-align:center;
		color:white;
		opacity:0.8;
		border:2px solid white;
		padding:50px 0px;
		}
	#button{
		width:250px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		}
	#ph{
		outline:0px;
		width:70px;
		padding:10px;
		border-radius:5px;
	}
	#phone{
		width:200px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		}
		#check{
	font-family:serif;
	font-size:18px;
}
	#rd{

	}
	#but{
		color:white;
		font-size:18px;
	}
	#butt{
		width:200px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		background-color:#0c6996;
		border:2px solid #01010c;
		color:aliceblue;
		font-size:18px;
		}
		.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: blue;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: white;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
	</style>
</head>  
<body> 
<div class="header">
<img src="images/logo.jpg" alt="logo" width="70" height="70"
style="margin-left:5px;
margin-top:4px;
margin-bottom:5px;border-radius:50%">
<div class="google">
<h1 style="margin-left:90px; margin-top:-50px; font-family:times new roman;font-size:40">Automated Sports</h1>
 </div>
 </div><br><br><br><br><br>""")
print("""
 <center>
<div class="container"> 
<h3><br><b>REGISTERATION</b></h3>
<form action="#" method="post" enctype="multipart/form-data" >
<table style="color:black;font-family:cursive;">
<tr>
<td align="left"><b><br>EventID:</b></td>
<td><input type="text" name="eid" id="eid" value="%s" readonly autocomplete="off"></td>
</tr>
<tr>
<td align="left"><b><br>SportsName:</b></td>
<td><input type="text" name="game" id="game" required></td>
</tr>

<tr>
<td align="left"><b><br>Date:</b></td>
<td><input type="date" name="date" id="date" required></td>
</tr>
<tr>
<td align="left"><b><br>Location:</b></td>
<td><input type="text" name="location" id="location" required></td>
</tr>
<tr>
<td><b>Profile:</b></td>
<td><br><input type="file" id="profile" name="profile"></td>
</tr>


</table><br>
<input type="submit" name="submit" id="submit" value="Register" class="btn float-right login_btn">
<input type="reset" value="Cancel" class="btn float-right login_btn">
</form>

</div> 
</center>
</body>  
</html>  
"""%(eid))
f = cgi.FieldStorage()
sub = f.getvalue("submit")
if sub != None:

    Eventid = f.getvalue("eid")
    SportsName = f.getvalue("game")
    Date = f.getvalue("date")
    Location = f.getvalue("location")
    profile = f['profile']
    if profile.filename:
        import os

        fp = os.path.basename(profile.filename)
        open("images/" + fp, "wb").write(profile.file.read())

        q = """insert into
        event_reg(eid,game,date,location,profile)
        values('%s','%s','%s','%s','%s')"""%(Eventid, SportsName,Date,Location, fp)
        cur.execute(q)
        conn.commit()
        conn.close()




        print("""
                            <script>
                			    alert("Registered successfully");
                                location.href="event_new.py";
                            </script>
                           """)
    else:
        print("""
                            <script>
                                alert("Login invalid");
                                location.href="event_reg.py";
                            </script>
                            """)
