#!C:/Users/DELL/AppData/Local/Programs/Python/Python39/python.exe
print("Content-type:text/html \r\n\r\n")
import cgi,cgitb;cgitb.enable()
import pymysql
conn=pymysql.connect(host="localhost",user="root",password="",database="fest")
cur=conn.cursor()
q1="""select max(id) from event_reg"""
cur.execute(q1)
r=cur.fetchone()
if r[0]!=None:
    n=r[0]
else:
    n=0
z=""
if n<10:
    z="000"
elif n<100:
    z="00"
elif n<1000:
    z="0"
else:
    z=""
eid="event"+z+str(n+1)
print("""
<html>  
<head>   
<title>Student registration</title>
<link rel="stylesheet" type="text/css" href="styles/styles1.css">
<link  rel="icon" type="logo/icon" href="images/logo.jpg">
<link rel="stylesheet" type="text/css" href="styles/css/bootstrap.min.css">
<script src="styles/js/jquery.min.js"></script>
<script src="styles/js/bootstrap.min.js"></script>
<style>
	* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Verdana,Grande,Fahoma,sans-serif;
}

.header {
  overflow: hidden;
  background-color:mediumseagreen;
  padding: 3px 10px;
}

.header a {
  float: left;
  color: blue;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }

  .header-right {
    float: none;
  }
}

	body{
		margin:0px;
		padding:0px;
		background-image:url('images/sports.jpg');
		background-repeat:no-repeat;
		background-size:100% 1500px;
		background-size:cover;
		}
	.simple-form{
		text-align:center;
		margin:100px 400px;
		}
	#registration{
		margin:auto;
		width:80%;
		background-color:gray;
		text-align:center;
		color:white;
		opacity:0.8;
		border:2px solid white;
		padding:50px 0px;
		}
	#button{
		width:250px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		}
	#ph{
		outline:0px;
		width:70px;
		padding:10px;
		border-radius:5px;
	}
	#phone{
		width:200px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		}
		#check{
	font-family:serif;
	font-size:18px;
}
	#rd{

	}
	#but{
		color:white;
		font-size:18px;
	}
	#butt{
		width:200px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		background-color:#0c6996;
		border:2px solid #01010c;
		color:aliceblue;
		font-size:18px;
		}
	</style>
</head>  
<body> 
<div class="header">
<img src="images/logo.jpg" alt="logo" width="70" height="70"
style="margin-left:5px;
margin-top:4px;
margin-bottom:5px;border-radius:50%">
<div class="google">
<h1 style="margin-left:90px; margin-top:-50px; font-family:times new roman;font-size:40">Sports</h1>
 </div>
 </div><br><br><br><br><br>""")
print("""
 <center>
<div class="container"> 
<h3><br><b>REGISTERATION</b></h3>
<form action="#" method="post" enctype="multipart/form-data" >
<table style="color:black;font-family:cursive;">
<tr>
<td align="left"><b><br>EventId:</b></td>
<td><input type="text" name="eid" id="eid" value="%s" readonly autocomplete="off"></td>
</tr>
<tr>
<td align="left"><b><br>Sports name:</b></td>
<td><input type="text" name="game" id="game" required></td>
</tr>
<tr>
<td align="left"><b><br>Date:</b></td>
<td><input type="email" placeholder="date" name="date" id="date" required></td>
</tr>
<tr>
<td align="left"><b><br>Location:</b></td>
<td><input type="type" name="location" id="location" required></td>
</tr></table>
<input type="submit" name="submit" id="submit" value="Register" class="btn float-right login_btn">
<input type="reset" value="Cancel" class="btn float-right login_btn">
</form>


</div> 
</center>
</body>  
</html>  """%(eid))
f=cgi.FieldStorage()
sub=f.getvalue("submit")
if sub != None:

    customerid=f.getvalue("custid")
    name=f.getvalue("name")
    dob=f.getvalue("dates")
    gender=f.getvalue("gm")
    uname=f.getvalue("uname")
    pwd=f.getvalue("pwd")
    email=f.getvalue("gmail")
    mobno=f.getvalue("number")
    profile=f['profile']
    if profile.filename:
        import os

        fp=os.path.basename(profile.filename)
        open("images/" + fp, "wb").write(profile.file.read())

        q="""insert into
        customer_reg(custid,name,dates,gm,uname,pwd,gmail,number,profile)
        values('%s','%s','%s','%s','%s','%s','%s','%s','%s')"""%(customerid,name,dob,gender,uname,pwd,email,mobno,fp)
        cur.execute(q)
        conn.commit()
        conn.close()

        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        mail_content = """Hello,%s
                          Username:%s
                          Password:%s
                        """%(name, uname, pwd)
        sender_address = 'budgetmartproject21@gmail.com'
        sender_pass = 'mart2021'
        receiver_address = email
        message = MIMEMultipart()
        message['From'] = sender_address
        message['To'] = receiver_address
        message['Subject'] = 'Registered Successfully!'
        message.attach(MIMEText(mail_content, 'plain'))
        session = smtplib.SMTP('smtp.gmail.com', 587)
        session.starttls()
        session.login(sender_address, sender_pass)
        text = message.as_string()
        session.sendmail(sender_address, receiver_address, text)
        session.quit()

        print("""
                            <script>
                			alert("Registered successfully");
                            location.href="customer_login.py";
                            </script>
                           """)
    else:
        print("""
                            <script>
                            alert("Login invalid");
                            location.href="customer_reg.py";
                            </script>
                            """)
