#!C:\Users\DELL\AppData\Local\Programs\Python\Python39\python.exe
print("Content-type:text/html \r\n\r\n")
import cgi, pymysql, cgitb;

cgitb.enable()
conn = pymysql.connect(host="localhost", user="root", password="", database="fest")
cur = conn.cursor()
print("""
<html lang="en">

<head>
    <title>sports</title>
<link rel="stylesheet" type="text/css" href="styles/bootstrap.min.css">
<link  rel="icon" type="logo/icon" href="images/logo.jpg">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="styles/styles/css/style.css">
</head>
<script src="styles/styles/js/jquery.min.js"></script>
<script src="styles/styles/js/bootstrap.min.js"></script>
<script>
function validate()
{
        var letters = /^[A-Za-z]+$/;
	    var password = /^(?=.[A-Za-z])(?=.\d)(?=.[@$!%#?&])[A-Za-z\d@$!%*#?&]{8,}$/;

  var a=document.getElementById('uname').value;
  var b=document.getElementById('psw').value;

	   if(a == "" and b == "")
	   {
	   alert("Enter the username and password");
	   return false;
	   }	   
}
</script>
</head>
<style>

*{
	padding:0;
	margin:0;
	}
	img{
	border-radius:50%;
	margin-left:40px;
	margin-top:10px;
	}
	.header1{
	height:100px;
	width:500%;
	position:fixed;
	background-color:mediumseagreen;
	}
	.google{
	color:white;
	position:absolute;
	top:20%;
	left:50px;
	}
body {
  font-family: "Lato",cursive;
}
body
{
background-image:url('images/bg4.jpg');
background-repeat:no-repeat;
background-size:cover;
}


.login {
    background-color:gray;
    width: 40%;
    margin: 80px auto;
    border-radius: 10px;
    padding: 20px;
    margin-top:148px;

}

.login>.row>h2 {
    margin: auto;
}

.btn-form {
    width: 100%;
    margin-top: 20px;
    background-color:powderblue;
}

</style>
<body>
<div class="full">
<div class="container-fluid" class="jumbotron text-center">
<div class="row" style="background-color:dodgerblue;">
<div class="col-sm-4"><img class="img-circle" height="80px" width="80px"
 src="images/logo.jpg" alt="logo"></div>
<div class="col-sm-12">
 <h1 style="margin-left:130px; margin-top:-60px; font-family:times new roman;font-size:40">Sports</h1></div>
</div>
</div>
</div>


    <div class="container">
        <div class="login">
            <div class="row">
               <fieldset> <legend>

<h2><center>FORGOT PASSWORD<img class="img-circle" src="images/avatar.jpg" alt="Avatar" class="avatar"  height="85px" width="85px">
</center></h2></legend><br>
               <form action="#" method="post" onsubmit="validate()">
                <div class="col-md-12">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="uname" name="uname" autocomplete="off" required>
                    <br>
                         </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                     <input type="submit" id="submit" value="update" name="submit" class="btn btn-outline-success btn-form">

                </div>
                <div class="col-md-6">
                   <input type="button"  value="cancel"  class="btn btn-outline-primary btn-form" onclick = "location.href ='user_login.py'">
                   </div> 
                   </div><br>

                </div>
</fieldset>
</body>
</html>""")

f = cgi.FieldStorage()
usr = f.getvalue("uname")
v = f.getvalue("submit")
if v != None:

    q = """select psw,gmail from sportshead_reg where uname='%s'""" % (usr)
    cur.execute(q)
    r = cur.fetchone()
    if r[0] != None:
        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        sender_address = 'techworldsoftware21@gmail.com'
        sender_pass = 'TechWorld@21'
        toaddress = r[1]
        msg = """
      Hi, Welcome %s
      password: %s
      """ % (usr, r[0])
        receiver_address = toaddress
        message = MIMEMultipart()
        message['From'] = sender_address
        message['To'] = receiver_address
        message['Subject'] = 'Registered Successfully!'
        message.attach(MIMEText(msg, 'plain'))
        session = smtplib.SMTP('smtp.gmail.com', 587)
        session.starttls()
        session.login(sender_address, sender_pass)
        text = message.as_string()
        session.sendmail(sender_address, receiver_address, text)
        session.quit()

        print("""
              <script>
                 alert("Updated successfully");

              </script>   
                 """)
