#!C:/Users/DELL/AppData/Local/Programs/Python/Python39/python.exe
print("Content-type:text/html \r\n\r\n")
import cgi, pymysql, cgitb;

cgitb.enable()
conn = pymysql.connect(host="localhost", user="root", password="", database="fest")
cur = conn.cursor()
f = cgi.FieldStorage()
id = f.getvalue("id")
q = """select * from student_reg where accept='Accepted'"""
cur.execute(q)
r = cur.fetchall()
cnt = 0
print("""
<html>
<html>
<head>
<title>Student</title>
<link rel="stylesheet" type="text/css" href="styles/bootstrap.min.css">
<link  rel="icon" type="logo/icon" href="images/logo.jpg">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="styles/styles/css/style.css">
</head>
<script src="styles/styles/js/jquery.min.js"></script>
<script src="styles/styles/js/bootstrap.min.js"></script>
<style>
*{
	padding:0;
	margin:0;
	}
	img{
	border-radius:50%;
	margin-left:40px;
	margin-top:10px;
	}
	.header1{
	height:100px;
	width:500%;
	position:fixed;
	background-color:mediumseagreen;
	}
	.google{
	color:white;
	position:absolute;
	top:20%;
	left:50px;
	}
body {
  font-family: "Lato",cursive;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: blue;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 40px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: white;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 10px;}
  .sidenav a {font-size: 18px;}
}
body
{
background-image:url('images/bg5.jpg');
background-repeat:no-repeat;
background-size:cover;
}
table,th,td
{
border-collapse:collapse;
border:2px solid-black;
padding:5px;
margin-left:30px;
}
</style>
<body>
<div class="full">
<div class="container-fluid" class="jumbotron text-center">
<div class="row" style="background-color:dodgerblue;">
<div class="col-sm-4"><img class="img-circle" height="80px" width="80px"
 src="images/logo.jpg" alt="logo"></div>

<div class="col-sm-12">
 <h1 style="margin-left:130px; margin-top:-60px; font-family:times new roman;font-size:40">Automated Sports</h1></div>
</div>
</div>
<div id="main">

  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
</div>
<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>


   </div>
</div>""")
print("""
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <li class="nav-item">
<a class="nav-link collapsed text-truncate"  href="sportshead_profile.py?id=%s" >
<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-home">Profile</i></span></a></li>
  <li class="nav-item">
<a class="nav-link collapsed text-truncate" href="#submenu1" data-toggle="collapse" data-target="#submenu1">

<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-product-hunt">Eventschedule<span class="caret"></span></i></span></a>
<div class="collapse" id="submenu1" aria-expanded="false">
<ul class="flex-column pl-2 nav"><br>
<li class="nav-item">
<a class="nav-link py-0" href="event_new.py">
<span style="color:brown;"><i class="fa fa-caret-right"><b> New</b></i></span></a></li></ul>
    
<ul class="flex-column pl-2 nav"><br>
<li class="nav-item">
<a class="nav-link py-0" href="event_existing.py">
<span style="color:brown;"><i class="fa fa-caret-right"><b> Existing</b></i></span></a></li></ul>
</div>
</li>
  <li class="nav-item">
<a class="nav-link collapsed text-truncate"  href="student_existing.py?id=%s" >
<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-home">Student details</i></span></a></li>
  <li class="nav-item">
<a class="nav-link collapsed text-truncate"  href="result.py?id=%s" >
<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-home">Result</i></span></a></li>
<li class="nav-item">
<a class="nav-link collapsed text-truncate" href="index.html">
<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-sign-out">Logout</i></span></a></li>
</ul>
</div>
<div class="col-sm-2">
<h5></h5>
<table border="2" width="100">
<tr>
<th>S.No</th>
<th>SportsheadId</th>
<th>Name</th>
<th>Email</th>
<th>DOB</th>
<th>Gender</th>
<th>Mobno</th>
<th>Address</th>
<th>Username</th>
<th>Password</th>
<th>Profile</th>
<tr>""")
for i in r:
    cnt = cnt + 1
    print("""
    <tr>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td>
    <td>%s</td> 
    <td>%s</td>
    <td><img src="images/%s" width=50" height="50" class="rounded-circle"></td>

    </tr>""" % (cnt, i[1], i[2], i[3], i[4], i[5], i[6], i[7], i[8], i[9], i[10]))
    print("""


</div>
</div>

</div>
</body>
</html>""")
