#!C:/Users/DELL/AppData/Local/Programs/Python/Python39/python.exe
print("content-type:text/html \r\n\r\n")
import cgi, pymysql, cgitb;
cgitb.enable()
conn = pymysql.connect(host="localhost", user="root", password="", database="fest")
cur = conn.cursor()
f = cgi.FieldStorage()
id = f.getvalue("id")
q = """select * from volunteer_reg where id=%s""" % (id)
cur.execute(q)
r = cur.fetchone()

print("""
<html>
<head>
<title>Volunteer</title>
<link rel="stylesheet" type="text/css" href="styles/bootstrap.min.css">
<link  rel="icon" type="logo/icon" href="images/logo.jpg">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="styles/styles/css/style.css">
</head>
<script src="styles/styles/js/jquery.min.js"></script>
<script src="styles/styles/js/bootstrap.min.js"></script>
<style>
*{
	padding:0;
	margin:0;
	}
	img{
	border-radius:50%;
	margin-left:40px;
	margin-top:10px;
	}
	.header1{
	height:100px;
	width:500%;
	position:fixed;
	background-color:mediumseagreen;
	}
	.google{
	color:white;
	position:absolute;
	top:20%;
	left:50px;
	}
body {
  font-family: "Lato",cursive;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: blue;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: white;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
body
{
background-image:url('images/cup.jpg');
background-repeat:no-repeat;
background-size:cover;
}
</style>
</head>
<body>
<div class="full">
<div class="container-fluid" class="jumbotron text-center">
<div class="row" style="background-color:dodgerblue;">
<div class="col-sm-4"><img class="img-circle" height="80px" width="80px"
 src="images/logo.jpg" alt="logo"></div>
<div class="col-sm-12">

 <h1 style="margin-left:130px; margin-top:-60px; font-family:times new roman;font-size:40">Automated Sports</h1></div>
</div>
</div>
</div>""")
print("""
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <li class="nav-item">
<a class="nav-link collapsed text-truncate" href="volunteer_profile.py?id=%s" >
<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-home">Profile</i></span></a></li>
  <li class="nav-item">
<a class="nav-link collapsed text-truncate" href="#submenu1" data-toggle="collapse" data-target="#submenu1">

<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-product-hunt">Student<span class="caret"></span></i></span></a>
<div class="collapse" id="submenu1" aria-expanded="false">
<ul class="flex-column pl-2 nav"><br>
<li class="nav-item">
<a class="nav-link py-0" href="volunteer_new.py?id=%s">
<span style="color:brown;"><i class="fa fa-caret-right"><b> New request</b></i></span></a></li></ul>

<ul class="flex-column pl-2 nav"><br>
<li class="nav-item">
<a class="nav-link py-0" href="volunteer_existing.py?id=%s">
<span style="color:brown;"><i class="fa fa-caret-right"><b> Existing</b></i></span></a></li>

</ul>
</div>
</li>

<li class="nav-item">
<a class="nav-link collapsed text-truncate" href="index.html">
<span class="d-none d-sm-inline" style="color:white;"><i class="fa fa-sign-out">Logout</i></span></a></li>
</ul>
</div>""" % (id, id, id))

print("""
<div class="col-sm-8">
</div>
<div class="col-sm-8">
<center><tr><h1 style="color:white">Welcome<td> %s</h2> </td></tr></center>""" % (r[2]))
print("""
</div>
</div>
</div>
</div>

<div id="main">

  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
</div>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
   </div>
</body>
</html>""")
