#!C:/Users/DELL/AppData/Local/Programs/Python/Python39/python.exe
print("Content-type:text/html \r\n\r\n")
import cgi, cgitb;

cgitb.enable()
import pymysql

conn = pymysql.connect(host="localhost", user="root", password="", database="fest")
cur = conn.cursor()
q1 = """select max(id) from volunteer_reg"""
cur.execute(q1)
r = cur.fetchone()
if r[0] != None:
    n = r[0]
else:
    n = 0
z = ""
if n < 10:
    z = "000"
elif n < 100:
    z = "00"
elif n < 1000:
    z = "0"
else:
    z = ""
vid = "vol"+z+str(n + 1)
print("""
<html>  
<head>   
<title>Volunteer registration</title>
<link rel="stylesheet" type="text/css" href="styles/styles1.css">
<link  rel="icon" type="logo/icon" href="images/logo.jpg">
<link rel="stylesheet" type="text/css" href="styles/css/bootstrap.min.css">
<script src="styles/js/jquery.min.js"></script>
<script src="styles/js/bootstrap.min.js"></script>
<style>
	* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Verdana,Grande,Fahoma,sans-serif;
}

.header {
  overflow: hidden;
  background-color:mediumseagreen;
  padding: 3px 10px;
}

.header a {
  float: left;
  color: blue;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }

  .header-right {
    float: none;
  }
}

	body{
		margin:0px;
		padding:0px;
		background-image:url('images/sports.jpg');
		background-repeat:no-repeat;
		background-size:100% 1500px;
		background-size:cover;
		}
	.simple-form{
		text-align:center;
		margin:100px 400px;
		}
	#registration{
		margin:auto;
		width:80%;
		background-color:gray;
		text-align:center;
		color:white;
		opacity:0.8;
		border:2px solid white;
		padding:50px 0px;
		}
	#button{
		width:250px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		}
	#ph{
		outline:0px;
		width:70px;
		padding:10px;
		border-radius:5px;
	}
	#phone{
		width:200px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		}
		#check{
	font-family:serif;
	font-size:18px;
}
	#rd{

	}
	#but{
		color:white;
		font-size:18px;
	}
	#butt{
		width:200px;
		padding:10px;
		border-radius:5px;
		outline:0px;
		background-color:#0c6996;
		border:2px solid #01010c;
		color:aliceblue;
		font-size:18px;
		}
	</style>
</head>  
<body> 
<div class="header">
<img src="images/logo.jpg" alt="logo" width="70" height="70"
style="margin-left:5px;
margin-top:4px;
margin-bottom:5px;border-radius:50%">
<div class="google">
<h1 style="margin-left:90px; margin-top:-50px; font-family:times new roman;font-size:40">Sports</h1>
 </div>
 </div><br><br><br><br><br>""")
print("""
 <center>
<div class="container"> 

<h3><br><b>REGISTERATION</b></h3>
<form action="#" method="post" enctype="multipart/form-data" >
<table style="color:black;font-family:cursive;">
<tr>
<td align="left"><b>VolunteerId:</b></td>
<td><input type="text" name="vid" id="vid" value="%s" readonly autocomplete="off"></td>
</tr>
<tr>
<td align="left"><b><br>Name:</br></b></td>
<td><input type="text" name="name" id="name" required></td>
</tr>
<tr>
<td align="left"><b><br>E-mail:</br></b></td>
<td><input type="email" placeholder="@gmail.com" name="gmail" id="gmail" required></td>
</tr>
<tr>
<td align="left"><b><br>DOB:</br></b></td>
<td><input type="date" name="dt" id="dt" required></td>
</tr>
<tr>
<td align="left"><b><br>Gender:</br></b></td>
<td><input type="radio" value="male" name="gen" id="gen">Male<input type="radio" value="female" name="gen" id="gen">Female</td>
</tr>
<tr>
<td align="left"><b><br>Mobile number:</br></b></td>
<td><input type="tel" name="number" id="number" required></td>
</tr>
<tr>
<td align="left"><b><br>Address:</br></b></td>
<td><input type="tel" name="address" id="address" required></td>
</tr>
<tr>
<td align="left"><b><br>Username:</br></b></td>"""%(vid))
print("""
<td><input type="text" name="uname" id="uname" value="%s" readonly autocomplete="off"></td>
</tr>
<tr>
<td align="left"><b><br>Password:</br></b></td>

<td><input type="password" name="psw" id="psw" required></td>
</tr>
<tr>
<td><b><br>Profile:</br></b></td>
<td><input type="file" id="profile" name="profile"></td>
</tr>
</table><br>
<input type="submit" name="submit" id="submit" value="Register" class="btn float-right login_btn">
<input type="reset" value="Cancel" class="btn float-right login_btn">
</form>
<a href="volunteer_login.py"><u><b>Existing user? Click to Login</b></u></a>
</div> 
</center>
</body>  
</html>  
""" % (vid))
f = cgi.FieldStorage()
sub = f.getvalue("submit")
if sub != None:

    volunteerid = f.getvalue("vid")
    name = f.getvalue("name")
    email = f.getvalue("gmail")
    dob = f.getvalue("dt")
    gender = f.getvalue("gen")
    mobno = f.getvalue("number")
    address = f.getvalue("address")
    uname = f.getvalue("uname")
    pwd = f.getvalue("psw")
    profile = f['profile']
    if profile.filename:
        import os

        fp = os.path.basename(profile.filename)
        open("images/" + fp, "wb").write(profile.file.read())

        q = """insert into
        volunteer_reg(vid,name,gmail,dt,gen,number,address,uname,psw,profile)
        values('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')""" % (
        volunteerid, name, email, dob, gender, mobno, address, uname, pwd, fp)
        cur.execute(q)
        conn.commit()
        conn.close()

        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText

        mail_content = """Hello,%s
                          Username:%s
                          Password:%s
                        """ % (name, uname, pwd)
        sender_address = 'sportsreg2021@gmail.com'
        sender_pass = 'play@1234'
        receiver_address = email
        message = MIMEMultipart()
        message['From'] = sender_address
        message['To'] = receiver_address
        message['Subject'] = 'Registered Successfully!'
        message.attach(MIMEText(mail_content, 'plain'))
        session = smtplib.SMTP('smtp.gmail.com', 587)
        session.starttls()
        session.login(sender_address, sender_pass)
        text = message.as_string()
        session.sendmail(sender_address, receiver_address, text)
        session.quit()

        print("""
                            <script>
                			    alert("Registered successfully");
                                location.href="volunteer_login.py";
                            </script>
                           """)
    else:
        print("""
                            <script>
                                alert("Login invalid");
                                location.href="volunteer_reg.py";
                            </script>
                            """)
